import { FormEvent, useEffect, useState } from "react";
import "./overrides.css";

type Section = "record" | "reports" | "delete" | "door" | "system" | "info";
type User = { enrollNumber: number; name: string | null; privilege?: 0 | 1; profilePhoto?: boolean; enrollment?: { privilege: 0 | 1; pin: boolean; fingerprint: boolean; face: boolean } };
type Attendance = { employeeId: number; name?: string | null; clock: number; eventCode?: number; verifyMode: number; timestampRaw?: string; date: string | null };
type DeviceClock = { year: number; month: number; day: number; hour: number; minute: number; second: number };
type Overview = { time: { year: number; month: number; day: number; hour: number; minute: number; second: number }; version: number; status: Record<string, number>; settings: Record<string, number> };
const menu: Array<{ id: Section; icon: string; title: string }> = [
  { id: "record", icon: "◉", title: "Kayıt" },
  { id: "reports", icon: "▤", title: "Raporlar" },
  { id: "door", icon: "▯", title: "Kapı" },
  { id: "system", icon: "⚙", title: "Sistem" }, { id: "info", icon: "ⓘ", title: "Sistem bilgisi" },
];
const modeName: Record<number, string> = { 0: "Bilinmeyen", 1: "Parmak izi", 2: "Şifre/PIN", 20: "Yüz", 21: "VFace" };

export default function App() {
  const [host, setHost] = useState("192.168.1.215"), [port, setPort] = useState("5006"), [section, setSection] = useState<string>("record");
  const [busy, setBusy] = useState(false), [connected, setConnected] = useState(false), [notice, setNotice] = useState<{ type: "ok" | "error"; text: string } | null>(null);
  const [users, setUsers] = useState<User[]>([]), [records, setRecords] = useState<Attendance[]>([]), [overview, setOverview] = useState<Overview | null>(null), [reportClock, setReportClock] = useState<DeviceClock | null>(null), [reportUserId, setReportUserId] = useState(""), [deviceTimeInput, setDeviceTimeInput] = useState(""), [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [deleteId, setDeleteId] = useState(""), [faceId, setFaceId] = useState(""), [editId, setEditId] = useState(""), [editName, setEditName] = useState(""), [form, setForm] = useState({ enrollNumber: "", name: "", password: "0", privilege: "0" });
  useEffect(() => { fetch("/api/config").then(r => r.json()).then(c => { setHost(c.host); setPort(String(c.port)); }).catch(() => undefined); }, []);
  useEffect(() => { const onClick = (event: MouseEvent) => { const target = event.target as HTMLElement; if (target.tagName !== "BUTTON" || target.textContent?.trim() !== "Güncelle") return; const row = target.closest(".user-row"); const idText = row?.querySelector(".user-main strong")?.textContent?.replace(/[^0-9]/g, ""); const id = Number(idText); if (!id) return; window.setTimeout(async () => { const answer = window.prompt(`#${id} yetkisi (0=Normal, 1=Admin):`, "0"); if (answer === null) return; const privilege = Number(answer); if (privilege !== 0 && privilege !== 1) return setNotice({ type: "error", text: "Yetki 0 veya 1 olmalı." }); try { const response = await fetch(`/api/users/${id}/privilege`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...connection, privilege }) }); if (!response.ok) throw new Error("Yetki güncellenemedi"); setNotice({ type: "ok", text: `#${id} yetkisi güncellendi.` }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Yetki güncellenemedi" }); } }, 100); }; document.addEventListener("click", onClick, true); return () => document.removeEventListener("click", onClick, true); }, [host, port]);
  useEffect(() => { const originalPrompt = window.prompt.bind(window); let lastRow: HTMLElement | null = null; const rememberRow = (event: MouseEvent) => { const target = event.target as HTMLElement; if (target.tagName === "BUTTON" && target.textContent?.trim() === "Güncelle") lastRow = target.closest(".user-row"); }; const promptWithCurrentPrivilege = (message?: string, fallback?: string) => { if (message?.includes("yetkisi") && lastRow) { const text = lastRow.textContent ?? ""; fallback = text.includes("Admin (1)") ? "1" : text.includes("Normal (0)") ? "0" : fallback; } return originalPrompt(message, fallback); }; document.addEventListener("click", rememberRow, true); window.prompt = promptWithCurrentPrivilege; return () => { document.removeEventListener("click", rememberRow, true); window.prompt = originalPrompt; }; }, []);
  useEffect(() => { document.querySelectorAll<HTMLElement>(".user-row").forEach((row, index) => { const user = users[index]; if (!user) return; const info = row.querySelector<HTMLElement>(".enrollment-info"); if (!info) return; let badge = info.querySelector<HTMLElement>(".privilege-info"); if (!badge) { badge = document.createElement("span"); badge.className = "privilege-info"; info.prepend(badge); } const privilege = user.privilege ?? user.enrollment?.privilege; badge.textContent = `Yetki: ${privilege === 1 ? "Admin (1)" : privilege === 0 ? "Normal (0)" : "Bilinmiyor"}`; }); }, [users]);
  const connection = { host, port: Number(port) }, query = `?host=${encodeURIComponent(host)}&port=${port}`;
  async function request(path: string, options: RequestInit = {}) { let response: Response; try { response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", ...(options.headers ?? {}) } }); } catch { throw new Error("Backend'e ulaşılamadı."); } const text = await response.text(); let data: any = {}; try { data = JSON.parse(text); } catch {} if (!response.ok) throw new Error(data.message ?? `API hatası (HTTP ${response.status})`); return data; }
  async function run(work: () => Promise<void>) { setBusy(true); setNotice(null); try { await work(); } catch (error) { setNotice({ type: "error", text: (error as Error).message }); } finally { setBusy(false); } }
  const test = () => run(async () => { const data = await request("/api/device/test", { method: "POST", body: JSON.stringify(connection) }); setConnected(true); setNotice({ type: "ok", text: data.message }); });
  const loadUsers = () => run(async () => { const data = await request(`/api/users${query}`); setUsers(data.users); setNotice({ type: "ok", text: `${data.count} kullanıcı listelendi.` }); });
  const loadOverview = () => run(async () => { const data = await request(`/api/device/overview${query}`); setOverview(data); const t = data.time as DeviceClock; setDeviceTimeInput(`${String(t.year).padStart(4, "0")}-${String(t.month).padStart(2, "0")}-${String(t.day).padStart(2, "0")}T${String(t.hour).padStart(2, "0")}:${String(t.minute).padStart(2, "0")}`); setNotice({ type: "ok", text: "Cihaz bilgileri okundu." }); });
  const loadRecordsFor = (userId = reportUserId) => run(async () => { const filter = userId.trim() ? `&userId=${encodeURIComponent(userId.trim())}` : ""; const data = await request(`/api/attendance${query}${filter}`); setRecords([...data.records].sort((a, b) => (b.date ? new Date(b.date).getTime() : Number.NEGATIVE_INFINITY) - (a.date ? new Date(a.date).getTime() : Number.NEGATIVE_INFINITY))); setReportClock(null); const userData = await request(`/api/users${query}`); setUsers(userData.users); setNotice({ type: "ok", text: `${data.count} devam kaydı okundu.` }); });
  const loadRecords = () => loadRecordsFor();
  const loadAllRecords = () => loadRecordsFor("");
  const control = (action: string) => run(async () => { const data = await request("/api/device/control", { method: "POST", body: JSON.stringify({ ...connection, action }) }); setNotice({ type: "ok", text: data.message }); });
  const setDeviceTime = () => { const parts = deviceTimeInput.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/); if (!parts) return setNotice({ type: "error", text: "Yeni cihaz tarihini ve saatini seçin." }); const [, year, month, day, hour, minute] = parts; return run(async () => { const data = await request("/api/device/time", { method: "POST", body: JSON.stringify({ ...connection, year: Number(year), month: Number(month), day: Number(day), hour: Number(hour), minute: Number(minute), second: 0 }) }); setOverview(current => current ? { ...current, time: data.time } : current); setNotice({ type: "ok", text: data.message }); }); };
  const addUser = (event: FormEvent) => { event.preventDefault(); const id = Number(form.enrollNumber); const pin = Number(form.password); if (!Number.isInteger(id) || id < 1 || !form.name.trim()) return setNotice({ type: "error", text: "Kullanıcı ID ve ad soyad zorunlu." }); if (!Number.isInteger(pin) || pin < 1 || pin > 0xffffffff) return setNotice({ type: "error", text: "PIN 1 ile 4294967295 arasında olmalı." }); return run(async () => { const data = await request("/api/users", { method: "POST", body: JSON.stringify({ ...connection, enrollNumber: id, password: pin, name: form.name, privilege: Number(form.privilege) }) }); setNotice({ type: "ok", text: data.verification?.warning ?? "PIN kaydı eklendi." }); setForm({ enrollNumber: "", name: "", password: "", privilege: "0" }); }); };
  const deleteUserById = (id: number) => { if (!window.confirm(`#${id} kullanıcısının PIN'i silinsin mi?`)) return; return run(async () => { const data = await request(`/api/users/${id}/password`, { method: "DELETE", body: JSON.stringify(connection) }); setNotice({ type: "ok", text: data.message }); setUsers(current => current.map(user => user.enrollNumber === id && user.enrollment ? { ...user, enrollment: { ...user.enrollment, pin: false } } : user)); setSelectedUser(current => current?.enrollNumber === id && current.enrollment ? { ...current, enrollment: { ...current.enrollment, pin: false } } : current); }); };
  const deletePin = () => { const id = Number(deleteId); if (!Number.isInteger(id) || id < 1) return setNotice({ type: "error", text: "Silinecek kullanıcı ID'sini girin." }); return deleteUserById(id); };
  const deleteFaceById = (id: number) => { if (!window.confirm(`#${id} kullanıcısının yüz biyometrisi silinsin mi?`)) return; return run(async () => { const data = await request(`/api/users/${id}/face`, { method: "DELETE", body: JSON.stringify(connection) }); setUsers(current => current.map(user => user.enrollNumber === id ? { ...user, enrollment: user.enrollment ? { ...user.enrollment, face: false } : user.enrollment } : user)); setSelectedUser(current => current?.enrollNumber === id && current.enrollment ? { ...current, enrollment: { ...current.enrollment, face: false } } : current); setNotice({ type: "ok", text: data.message }); }); };
  const deleteFingerprintById = (id: number) => { if (!window.confirm(`#${id} kullanıcısının parmak izi silinsin mi?`)) return; return run(async () => { const data = await request(`/api/users/${id}/fingerprint`, { method: "DELETE", body: JSON.stringify(connection) }); setUsers(current => current.map(user => user.enrollNumber === id ? { ...user, enrollment: user.enrollment ? { ...user.enrollment, fingerprint: false } : user.enrollment } : user)); setSelectedUser(current => current?.enrollNumber === id && current.enrollment ? { ...current, enrollment: { ...current.enrollment, fingerprint: false } } : current); setNotice({ type: "ok", text: data.message }); }); };
  const deleteFace = () => { const id = Number(faceId); if (!Number.isInteger(id) || id < 1) return setNotice({ type: "error", text: "Yüz biyometrisi silinecek kullanıcı ID'sini girin." }); return deleteFaceById(id); };
  const updateUserById = (id: number, currentName: string | null) => { const name = window.prompt(`#${id} için yeni ad soyad:`, currentName ?? ""); if (name === null) return; if (!name.trim()) return setNotice({ type: "error", text: "Yeni ad zorunlu." }); return run(async () => { const data = await request("/api/users/" + id, { method: "PATCH", body: JSON.stringify({ ...connection, name: name.trim() }) }); setNotice({ type: "ok", text: data.message }); setUsers(current => current.map(user => user.enrollNumber === id ? { ...user, name: name.trim() } : user)); }); };
  const updateName = () => { const id = Number(editId); if (!Number.isInteger(id) || id < 1 || !editName.trim()) return setNotice({ type: "error", text: "Kullanıcı ID ve yeni ad zorunlu." }); return updateUserById(id, editName); };
  const updatePinById = (id: number) => { const pin = window.prompt(`#${id} için yeni PIN:`, ""); if (pin === null) return; const password = Number(pin); if (!Number.isInteger(password) || password < 1 || password > 0xffffffff) return setNotice({ type: "error", text: "PIN 1 ile 4294967295 arasında olmalı." }); return run(async () => { const data = await request(`/api/users/${id}/password`, { method: "PATCH", body: JSON.stringify({ ...connection, password }) }); setNotice({ type: "ok", text: data.message }); }); };
  const updatePrivilegeById = (id: number, current: 0 | 1) => { const privilege = current === 1 ? 0 : 1; if (!window.confirm(`#${id} yetkisi ${privilege === 1 ? "admin" : "normal kullanıcı"} olsun mu?`)) return; return run(async () => { const data = await request(`/api/users/${id}/privilege`, { method: "PATCH", body: JSON.stringify({ ...connection, privilege }) }); setNotice({ type: "ok", text: data.message }); setUsers(users => users.map(user => user.enrollNumber === id ? { ...user, enrollment: user.enrollment ? { ...user.enrollment, privilege } : user.enrollment } : user)); }); };
  const time = overview && `${String(overview.time.day).padStart(2, "0")}.${String(overview.time.month).padStart(2, "0")}.${overview.time.year} ${String(overview.time.hour).padStart(2, "0")}:${String(overview.time.minute).padStart(2, "0")}:${String(overview.time.second).padStart(2, "0")}`;
  const action = (label: string, onClick: (() => void) | ((event: FormEvent) => void), danger = false) => <button className={danger ? "action danger" : "action"} disabled={busy} onClick={onClick as any}>{label}</button>;
  const pane = () => {
    if (selectedUser) return <div className="user-detail-panel"><div className="user-detail-head"><div><p className="eyebrow">KULLANICI DETAYI</p><h3>#{selectedUser.enrollNumber} · {selectedUser.name ?? "Ad okunamadı"}</h3></div><button className="action subtle" onClick={() => setSelectedUser(null)}>Kapat</button></div><div className="detail-methods"><div><b>PIN</b><span>{selectedUser.enrollment?.pin ? "Tanımlı" : "Yok"}</span>{selectedUser.enrollment?.pin && action("PIN sil", () => deleteUserById(selectedUser.enrollNumber), true)}</div><div><b>Parmak izi</b><span>{selectedUser.enrollment?.fingerprint ? "Tanımlı" : "Yok"}</span>{selectedUser.enrollment?.fingerprint && action("Parmak izini sil", () => deleteFingerprintById(selectedUser.enrollNumber), true)}</div><div><b>Yüz biyometrisi</b><span>{selectedUser.enrollment?.face ? "Tanımlı" : "Yok"}</span>{selectedUser.enrollment?.face && action("Yüzü sil", () => deleteFaceById(selectedUser.enrollNumber), true)}</div><div><b>Profil fotoğrafı</b><span>{selectedUser.profilePhoto ? "Yüklü" : "Yok"}</span></div><div><b>Kart</b><span>Durum okunmuyor</span><button className="action" disabled>Silme paketi bekleniyor</button></div></div></div>;
    if (section === "record") return <><h3>PIN kullanıcı kaydı</h3><p>Cihaza yalnızca doğrulanmış PIN kullanıcıları eklenir.</p><div className="new-user-form"><div className="form-grid"><label>Kullanıcı ID<input required type="number" min="1" value={form.enrollNumber} onChange={e => setForm({ ...form, enrollNumber: e.target.value })} /></label><label>Ad soyad<input required maxLength={63} placeholder="Örn. Ahmet Yılmaz" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label></div><div className="form-grid"><label>Yetki<select value={form.privilege} onChange={e => setForm({ ...form, privilege: e.target.value })}><option value="0">Kullanıcı</option><option value="1">Admin</option></select></label><label>Şifre (PIN)<input required type="number" min="1" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label></div><div className="action-row">{action("PIN kullanıcısı ekle", addUser)}</div></div><div className="action-row">{action("Kullanıcıları oku", loadUsers)}</div>{users.length > 0 && <UserTable users={users} busy={busy} onSelectUser={setSelectedUser} onDeleteUser={deleteUserById} onUpdateUser={updateUserById} onUpdatePin={updatePinById} onUploadPhoto={() => undefined} />}</>;
    if (section === "reports") return <><h3>Raporlar</h3><p>Doğrulanmış 20 baytlık devam kayıtlarını cihazdan okuyun.</p><div className="report-actions"><div className="report-action-card"><span>Tüm cihaz kayıtları</span>{action("Tüm logları oku", loadAllRecords)}</div><div className="report-action-card"><span>Belirli kullanıcı</span><div className="inline-form"><input value={reportUserId} onChange={e => setReportUserId(e.target.value)} type="number" min="1" placeholder="Kullanıcı ID" />{action("Kullanıcı loglarını oku", loadRecords)}</div></div></div>{records.length > 0 && <div className="report-summary"><h2>Rapor özeti</h2><p>{records.length} log kaydı okundu.</p><AttendanceTable records={records} users={users} /></div>}</>;
    if (section === "delete") return <><h3>Kullanıcı ve biyometri silme</h3><p>PIN veya yüz biyometrisi kaydını silin.</p><div className="inline-form"><input value={deleteId} onChange={e => setDeleteId(e.target.value)} type="number" min="1" placeholder="Kullanıcı ID" />{action("PIN'i sil", deletePin, true)}</div><div className="inline-form"><input value={faceId} onChange={e => setFaceId(e.target.value)} type="number" min="1" placeholder="Kullanıcı ID" />{action("Yüz biyometrisini sil", deleteFace, true)}</div></>;
    if (section === "door") return <><h3>Kapı kontrolü</h3><p>Doğrulanmış E1 komutu ile kapı durumunu değiştirin.</p><div className="action-row">{action("Kapıyı aç", () => control("door-open"))}{action("Kapıyı kapat", () => control("door-close"))}{action("Otomatik kapanma", () => control("door-auto"))}</div></>;
    if (section === "system") return <><h3>Sistem</h3><p>Cihazı geçici olarak etkinleştirin veya devre dışı bırakın; saati okuyup güncelleyebilirsiniz.</p><div className="action-row">{action("Cihazı etkinleştir", () => control("enable"))}{action("Cihazı devre dışı bırak", () => control("disable"), true)}</div><div className="inline-form device-time-form"><input type="datetime-local" value={deviceTimeInput} onChange={e => setDeviceTimeInput(e.target.value)} aria-label="Yeni cihaz tarihi ve saati" />{action("Cihaz saatini oku", loadOverview)}{action("Cihaz saatini güncelle", setDeviceTime)}</div>{overview && <div className="readout">Cihaz saati <b>{time}</b></div>}</>;
    return <><h3>Sistem bilgisi</h3><p>Sürüm, makine numarası ve doğrulanmış cihaz sayaçlarını okuyun.</p><div className="action-row">{action("Sistem bilgilerini oku", loadOverview)}</div>{overview && <div className="metrics">{[["Sürüm", overview.version], ["Makine no", overview.settings.machineNumber], ["Yönetici", overview.status.managers], ["Normal kullanıcı", overview.status.users], ["PIN", overview.status.passwords], ["Devam kaydı", overview.status.attendanceLogs]].map(([label, value]) => <span key={String(label)}>{label}<b>{value}</b></span>)}</div>}</>;
  };
  return <main><header><div><p className="eyebrow">FKATTEND / RAW TCP</p><h1>Cihaz Yönetim Paneli</h1></div><div className={connected ? "connection-state ready" : "connection-state"}><i></i>{connected ? "Bağlantı doğrulandı" : "Bağlantı doğrulanmadı"}</div></header><section className="connection card"><div className="connection-fields"><label>IP adresi<input value={host} onChange={e => setHost(e.target.value)} /></label><label>TCP port<input value={port} onChange={e => setPort(e.target.value)} /></label><label className="udp"><input type="checkbox" disabled /> UDP kullan <small>Doğrulanmış paket yok</small></label></div><div className="action-row">{action("Bağlan", test)}<button className="action subtle" onClick={() => { setConnected(false); setNotice(null); }}>Durumu temizle</button></div></section><section className="card menu-card"><div className="menu-head"><div><p className="eyebrow">CİHAZ MENÜSÜ</p><h2>İşlevler</h2></div><p>İşlemleri doğrulanmış TCP paket kategorilerinden seçin.</p></div><div className="menu-grid">{menu.map(item => <button key={item.id} className={section === item.id ? "menu-item active" : "menu-item"} onClick={() => setSection(item.id)}><i>{item.icon}</i><span>{item.title}</span></button>)}</div><div className="operation-pane">{pane()}</div></section>{section === "record" && <section id="new-user" className="card form-card"><p className="eyebrow">YENİ KAYIT</p><h2>PIN kullanıcısı ekle</h2><form onSubmit={addUser}><div className="form-grid"><label>Kullanıcı ID<input required type="number" min="1" value={form.enrollNumber} onChange={e => setForm({ ...form, enrollNumber: e.target.value })} /></label><label>PIN / Şifre<input required type="number" min="0" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label></div><label>Ad soyad<input required maxLength={63} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Yetki<select value={form.privilege} onChange={e => setForm({ ...form, privilege: e.target.value })}><option value="0">Normal kullanıcı</option><option value="1">Yönetici</option></select></label><button className="action primary" disabled={busy}>PIN kullanıcısını ekle</button></form></section>}{notice && <div className={`notice ${notice.type}`}>{notice.text}<button onClick={() => setNotice(null)}>×</button></div>}</main>;
}

function UserTable({ users, busy, onSelectUser, onDeleteUser, onUpdateUser, onUpdatePin, onUploadPhoto }: { users: User[]; busy: boolean; onSelectUser: (user: User) => void; onDeleteUser: (id: number) => void; onUpdateUser: (id: number, name: string | null) => void; onUpdatePin: (id: number) => void; onUploadPhoto: (id: number, file: File | null) => void }) { const [files, setFiles] = useState<Record<number, File | null>>({}); return <div className="user-list">{users.map(user => <article className="user-row" key={user.enrollNumber}><div className="user-main"><button className="user-detail-link" onClick={() => onSelectUser(user)}><strong>#{user.enrollNumber}</strong><span>{user.name ?? "Ad okunamadı"}</span></button><div className="enrollment-info"><span>Giriş yöntemleri</span><span>PIN: {user.enrollment?.pin ? "Var" : "Yok"}</span><span>Parmak izi: {user.enrollment?.fingerprint ? "Var" : "Yok"}</span><span>Yüz: {user.enrollment?.face ? "Var" : "Yok"}</span><span>Profil fotoğrafı: {user.profilePhoto ? "Var" : "Yok"}</span></div></div><div className="user-actions"><div className="action-group"><small>Kullanıcı</small><button className="action" disabled={busy} onClick={() => onUpdateUser(user.enrollNumber, user.name)}>Güncelle</button><button className="action danger" disabled={busy} onClick={() => onDeleteUser(user.enrollNumber)}>Sil</button></div><div className="action-group"><small>PIN</small><button className="action" disabled={busy} onClick={() => onUpdatePin(user.enrollNumber)}>PIN güncelle</button><button className="action danger" disabled={busy} onClick={() => onDeleteUser(user.enrollNumber)}>PIN sil</button></div><div className="action-group"><small>Profil fotoğrafı</small><label className="file-picker"><input type="file" accept="image/jpeg" disabled={busy} onChange={event => setFiles({ ...files, [user.enrollNumber]: event.target.files?.[0] ?? null })} /><span>{files[user.enrollNumber]?.name ?? "JPEG seç"}</span></label><button className="action" disabled={busy || !files[user.enrollNumber]} onClick={() => onUploadPhoto(user.enrollNumber, files[user.enrollNumber] ?? null)}>Fotoğraf yükle</button></div></div></article>)}</div>; }
function AttendanceTable({ records, users = [] }: { records: Attendance[]; users?: User[] }) { return <div className="table-wrap"><table><thead><tr><th>KULLANICI</th><th>ZAMAN</th><th>DOĞRULAMA</th><th>G/Ç</th></tr></thead><tbody>{records.map((record, index) => { const user = users.find(item => Number(item.enrollNumber) === Number(record.employeeId)); const name = record.name ?? user?.name; return <tr key={`${record.employeeId}-${index}`}><td>{name ? `#${record.employeeId} — ${name}` : "Kullanıcı adı okunamadı"}</td><td>{record.date ? new Date(record.date).toLocaleString("tr-TR") : "—"}</td><td>{modeName[record.verifyMode] ?? `Bilinmeyen (${record.verifyMode})`}</td><td>{record.clock}</td></tr>; })}</tbody></table></div>; }
