import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
void main()=>runApp(const MaterialApp(debugShowCheckedModeBanner:false,home:Home()));
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_S();}
class _S extends State<Home>{final api=TextEditingController(text:'http://192.168.1.227:3001'),host=TextEditingController(text:'192.168.1.215'),port=TextEditingController(text:'5006');bool connected=false,busy=false;String msg='Backend adresini girin.';int tab=0;List users=[],logs=[];Map<String,dynamic>? info;Map<String,dynamic> get conn=>{'host':host.text.trim(),'port':int.tryParse(port.text)??5006};Api get client=>Api(api.text.trim());
 Future<void> run(Future<void> Function() f)async{setState(()=>busy=true);try{await f();}catch(e){setState(()=>msg=e.toString().replaceFirst('Exception: ',''));}if(mounted)setState(()=>busy=false);}
 Future<void> connect()async{await run(()async{final d=await client.post('/api/device/test',conn);setState(()=>connected=true);msg=d['message']??'Bağlantı başarılı.';});}
 Future<void> readUsers()=>run(()async{final d=await client.get('/api/users',conn);users=d['users'] as List;msg='${d['count']} kullanıcı listelendi.';});
 Future<void> readLogs()=>run(()async{final d=await client.get('/api/attendance',conn);logs=List.from(d['records'] as List)..sort((a,b)=>(b['date']??'').toString().compareTo((a['date']??'').toString()));msg='${d['count']} log okundu.';});
 Future<void> control(String a)=>run(()async{final d=await client.post('/api/device/control',{...conn,'action':a});msg=d['message']??'Komut gönderildi.';});
 @override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('XFace43 Mobil')),body:ListView(padding:const EdgeInsets.all(16),children:[_connection(),Card(child:Padding(padding:const EdgeInsets.all(12),child:Text(msg))),if(connected)_module()]),bottomNavigationBar:connected?NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.people),label:'Kullanıcılar'),NavigationDestination(icon:Icon(Icons.list),label:'Raporlar'),NavigationDestination(icon:Icon(Icons.door_front_door),label:'Kapı'),NavigationDestination(icon:Icon(Icons.settings),label:'Sistem')]):null);}
 Widget _connection()=>Card(child:Padding(padding:const EdgeInsets.all(14),child:connected?Row(children:[const Icon(Icons.check_circle,color:Colors.green),const SizedBox(width:8),const Expanded(child:Text('Cihaza bağlı')),OutlinedButton(onPressed:busy?null:()=>setState(()=>connected=false),child:const Text('Bağlantıyı kes'))]):Column(children:[TextField(controller:api,decoration:const InputDecoration(labelText:'Backend API adresi')),Row(children:[Expanded(child:TextField(controller:host,decoration:const InputDecoration(labelText:'Cihaz IP adresi'))),const SizedBox(width:8),SizedBox(width:90,child:TextField(controller:port,decoration:const InputDecoration(labelText:'TCP port')))]),const SizedBox(height:10),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:connect,child:const Text('Bağlan')))])));
 Widget _module(){if(tab==0)return Column(children:[FilledButton.tonal(onPressed:busy?null:readUsers,child:const Text('Kullanıcıları oku')), ...users.map((u)=>ListTile(title:Text('#${u['enrollNumber']} · ${u['name']??''}'),subtitle:Text('PIN: ${u['enrollment']?['pin']==true?'Var':'Yok'} · Parmak izi: ${u['enrollment']?['fingerprint']==true?'Var':'Yok'} · Yüz: ${u['enrollment']?['face']==true?'Var':'Yok'}')))]);if(tab==1)return Column(children:[FilledButton.tonal(onPressed:busy?null:readLogs,child:const Text('Tüm logları oku')),...logs.take(50).map((x)=>ListTile(title:Text('Kullanıcı #${x['employeeId']}'),subtitle:Text('${x['date']??''} · ${_mode(x['verifyMode'])}')))]);if(tab==2)return Wrap(spacing:8,children:[_b('Kapıyı aç','door-open'),_b('Kapıyı kapat','door-close'),_b('Otomatik kapanma','door-auto')]);return Column(children:[_b('Cihazı etkinleştir','enable'),_b('Cihazı devre dışı bırak','disable'),_b('Cihaz saatini oku','overview')]);}
 String _mode(dynamic m)=>{1:'Parmak izi',2:'PIN / Şifre',20:'Yüz',21:'VFace'}[m]??'Bilinmeyen';Widget _b(String t,String a)=>FilledButton.tonal(onPressed:busy?null:()=>a=='overview'?run(()async{info=await client.get('/api/device/overview',conn);msg='Cihaz bilgileri okundu.';}):control(a),child:Text(t));
}
class Api{Api(this.base);final String base;Uri u(String p,[Map<String,dynamic>?q])=>Uri.parse(base+p).replace(queryParameters:q?.map((k,v)=>MapEntry(k,v.toString())));Future<Map<String,dynamic>>get(String p,Map<String,dynamic>q)=>req('GET',u(p,q));Future<Map<String,dynamic>>post(String p,Map<String,dynamic>b)=>req('POST',u(p),b);Future<Map<String,dynamic>>req(String m,Uri u,[Map<String,dynamic>?b])async{final c=HttpClient();try{final r=await c.openUrl(m,u);r.headers.contentType=ContentType.json;if(b!=null)r.write(jsonEncode(b));final s=await r.close(),t=await utf8.decoder.bind(s).join();final d=Map<String,dynamic>.from(jsonDecode(t));if(s.statusCode>=300)throw Exception(d['message']);return d;}finally{c.close(force:true);}}}
