import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';

void main() => runApp(const XFaceMobileApp());
class XFaceMobileApp extends StatelessWidget { const XFaceMobileApp({super.key}); @override Widget build(BuildContext c) => MaterialApp(debugShowCheckedModeBanner:false,title:'XFace43 Mobil',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff21b8ad),brightness:Brightness.dark),scaffoldBackgroundColor:const Color(0xff06101e),useMaterial3:true),home:const DevicePage()); }
class DevicePage extends StatefulWidget { const DevicePage({super.key}); @override State<DevicePage> createState()=>_DevicePageState(); }
class _DevicePageState extends State<DevicePage> {
 final _api=TextEditingController(text:'http://192.168.1.227:3001'),_host=TextEditingController(text:'192.168.1.215'),_port=TextEditingController(text:'5006'),_id=TextEditingController(),_name=TextEditingController(),_pin=TextEditingController(); bool _busy=false,_connected=false; String _message='Backend adresini girin ve bağlantıyı doğrulayın.'; int _tab=0; List<Map<String,dynamic>> _users=[],_attendance=[]; Map<String,dynamic>? _overview; Map<String,dynamic> get _connection=>{'host':_host.text.trim(),'port':int.tryParse(_port.text)??5006}; ApiClient get _client=>ApiClient(_api.text.trim());
 Future<void> _run(Future<void> Function() w)async{setState(()=>_busy=true);try{await w();}catch(e){_message=e.toString().replaceFirst('Exception: ','');}if(mounted)setState(()=>_busy=false);}
 Future<void> _test()=>_run(()async{final d=await _client.post('/api/device/test',_connection);_connected=true;_message=d['message']??'Bağlantı doğrulandı.';});
 Future<void> _readUsers()=>_run(()async{final d=await _client.get('/api/users',_connection);_users=List<Map<String,dynamic>>.from((d['users'] as List).map((e)=>Map<String,dynamic>.from(e)));_message='${d['count']} kullanıcı listelendi.';});
 Future<void> _readOverview()=>_run(()async{_overview=await _client.get('/api/device/overview',_connection);_message='Cihaz bilgileri okundu.';});
 Future<void> _readAttendance()=>_run(()async{final d=await _client.get('/api/attendance',_connection);_attendance=List<Map<String,dynamic>>.from((d['records'] as List).map((e)=>Map<String,dynamic>.from(e)));_attendance.sort((a,b)=>(b['date']??'').toString().compareTo((a['date']??'').toString()));_message='${d['count']} devam kaydı okundu.';});
 Future<void> _control(String a)=>_run(()async{final d=await _client.post('/api/device/control', {..._connection,'action':a});_message=d['message']??'Komut gönderildi.';});
 Future<void> _addUser()async{final id=int.tryParse(_id.text),pin=int.tryParse(_pin.text);if(id==null||id<1||_name.text.trim().isEmpty||pin==null||pin<1){setState(()=>_message='ID, ad soyad ve geçerli PIN girin.');return;}await _run(()async{final d=await _client.post('/api/users', {..._connection,'enrollNumber':id,'name':_name.text.trim(),'password':pin,'privilege':0});_message=d['message']??'PIN kullanıcısı eklendi.';_id.clear();_name.clear();_pin.clear();});}
 Future<void> _deleteMethod(int id,String m)async{await _run(()async{final d=await _client.delete('/api/users/$id/$m',_connection);_message=d['message']??'Kayıt silindi.';await _readUsers();});}
 void _details(Map<String,dynamic> u){showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>_UserDetail(user:u,busy:_busy,onDelete:(m){Navigator.pop(context);_deleteMethod(u['enrollNumber'] as int,m);},onUpdatePin:(){Navigator.pop(context);_updatePin(u['enrollNumber'] as int);}));}
 Future<void> _updatePin(int id)async{final c=TextEditingController();final v=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:Text('#$id PIN güncelle'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Yeni PIN')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('İptal')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('Kaydet'))]));if(v==null)return;await _run(()async{final d=await _client.patch('/api/users/$id/password',{..._connection,'password':int.parse(v)});_message=d['message']??'PIN güncellendi.';});}
 @override void dispose(){_api.dispose();_host.dispose();_port.dispose();_id.dispose();_name.dispose();_pin.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('XFace43 Mobil'),backgroundColor:const Color(0xff0b1d32)),body:SafeArea(child:ListView(padding:const EdgeInsets.all(14),children:[_connectionCard(),_Card(child:Text(_message)),_module()])),bottomNavigationBar:NavigationBar(selectedIndex:_tab,onDestinationSelected:(i)=>setState(()=>_tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.people),label:'Kullanıcılar'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Raporlar'),NavigationDestination(icon:Icon(Icons.door_front_door),label:'Kapı'),NavigationDestination(icon:Icon(Icons.settings),label:'Sistem'),NavigationDestination(icon:Icon(Icons.info),label:'Bilgi')]));
 Widget _connectionCard()=>_Card(child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('BACKEND BAĞLANTISI',style:TextStyle(color:Color(0xff55e5d5),fontSize:11,fontWeight:FontWeight.bold))),TextField(controller:_api,decoration:const InputDecoration(labelText:'Node API adresi')),Row(children:[Expanded(child:TextField(controller:_host,decoration:const InputDecoration(labelText:'Cihaz IP'))),const SizedBox(width:8),SizedBox(width:88,child:TextField(controller:_port,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Port')))]),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.icon(onPressed:_busy?null:_test,icon:const Icon(Icons.link),label:const Text('Bağlan'))),if(_connected)const SizedBox(width:8),if(_connected)OutlinedButton(onPressed:()=>setState(()=>_connected=false),child:const Text('Kes'))])));
 Widget _module(){if(_tab==0)return return_users();if(_tab==1)return _reports();if(_tab==2)return _door();if(_tab==3)return _system();return _info();}
 Widget return_users()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_Card(child:Column(children:[const Align(alignment:Alignment.centerLeft,child:Text('PIN KULLANICI KAYDI')),TextField(controller:_id,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Kullanıcı ID')),TextField(controller:_name,decoration:const InputDecoration(labelText:'Ad soyad')),TextField(controller:_pin,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'PIN')),const SizedBox(height:8),Align(alignment:Alignment.centerLeft,child:FilledButton(onPressed:_busy?null:_addUser,child:const Text('PIN kullanıcısı ekle')))])),FilledButton.tonalIcon(onPressed:_busy?null:_readUsers,icon:const Icon(Icons.refresh),label:const Text('Kullanıcıları oku')),if(_users.isNotEmpty)_Card(child:Column(children:[Text('Kullanıcılar (${_users.length})'),const Divider(),..._users.map((u)=>ListTile(onTap:()=>_details(u),leading:Text('#${u['enrollNumber']}',style:const TextStyle(color:Color(0xff55e5d5),fontWeight:FontWeight.bold)),title:Text(u['name']??'Ad okunamadı'),subtitle:Text('PIN ${u['enrollment']?['pin']==true?'Var':'Yok'} · Parmak izi ${u['enrollment']?['fingerprint']==true?'Var':'Yok'} · Yüz ${u['enrollment']?['face']==true?'Var':'Yok'}'),trailing:const Icon(Icons.chevron_right)))]))]);
 Widget _reports()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[FilledButton.tonalIcon(onPressed:_busy?null:_readAttendance,icon:const Icon(Icons.download),label:const Text('Tüm logları oku')),if(_attendance.isNotEmpty)_Card(child:Column(children:[Text('Rapor (${_attendance.length})'),const Divider(),..._attendance.take(100).map((r)=>ListTile(title:Text('Kullanıcı #${r['employeeId']}'),subtitle:Text('${r['date']??'Zaman yok'} · Doğrulama ${r['verifyMode']}')))]))]);
 Widget _door()=>_Card(child:Wrap(spacing:8,runSpacing:8,children:[_button('Kapıyı aç',Icons.lock_open,()=>_control('door-open')),_button('Kapıyı kapat',Icons.lock,()=>_control('door-close')),_button('Otomatik kapanma',Icons.timer,()=>_control('door-auto'))]));
 Widget _system()=>_Card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_button('Cihazı etkinleştir',Icons.power,()=>_control('enable')),_button('Cihazı devre dışı bırak',Icons.power_off,()=>_control('disable')),_button('Cihaz saatini oku',Icons.schedule,_readOverview),if(_overview!=null)_Overview(data:_overview!)])); Widget _info()=>_Card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[FilledButton.tonalIcon(onPressed:_busy?null:_readOverview,icon:const Icon(Icons.info),label:const Text('Sistem bilgilerini oku')),if(_overview!=null)_Overview(data:_overview!)])); Widget _button(String t,IconData i,Future<void> Function() f)=>FilledButton.tonalIcon(onPressed:_busy?null:f,icon:Icon(i),label:Text(t));
}
class _UserDetail extends StatelessWidget{const _UserDetail({required this.user,required this.busy,required this.onDelete,required this.onUpdatePin});final Map<String,dynamic> user;final bool busy;final void Function(String) onDelete;final VoidCallback onUpdatePin;@override Widget build(BuildContext c){final e=Map<String,dynamic>.from(user['enrollment']??{});return Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('#${user['enrollNumber']} · ${user['name']??'Ad okunamadı'}',style:Theme.of(c).textTheme.titleLarge),_m(c,'PIN',e['pin']==true,onUpdatePin,()=>onDelete('password')),_m(c,'Parmak izi',e['fingerprint']==true,null,()=>onDelete('fingerprint')),_m(c,'Yüz biyometrisi',e['face']==true,null,()=>onDelete('face'))]));}Widget _m(BuildContext c,String n,bool x,VoidCallback? up,VoidCallback del)=>ListTile(title:Text(n),subtitle:Text(x?'Tanımlı':'Yok'),trailing:x?Wrap(children:[if(up!=null)IconButton(onPressed:busy?null:up,icon:const Icon(Icons.edit)),IconButton(onPressed:busy?null:del,icon:const Icon(Icons.delete,color:Colors.redAccent))]):null);}}
class _Overview extends StatelessWidget{const _Overview({required this.data});final Map<String,dynamic> data;@override Widget build(BuildContext c){final t=Map<String,dynamic>.from(data['time']??{}),s=Map<String,dynamic>.from(data['status']??{});return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Divider(),Text('Cihaz saati: ${t['day']}.${t['month']}.${t['year']} ${t['hour']}:${t['minute']}:${t['second']}'),Text('Sürüm: ${data['version']}'),Text('Kullanıcı: ${s['users']} · Yönetici: ${s['managers']}'),Text('PIN: ${s['passwords']} · Log: ${s['attendanceLogs']}')]);}}
class _Card extends StatelessWidget{const _Card({required this.child});final Widget child;@override Widget build(BuildContext c)=>Card(color:const Color(0xff0c1c31),margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(14),child:child));}
class ApiClient{ApiClient(this.baseUrl);final String baseUrl;Uri _uri(String p,[Map<String,dynamic>?q])=>Uri.parse(baseUrl+p).replace(queryParameters:q?.map((k,v)=>MapEntry(k,v.toString())));Future<Map<String,dynamic>>get(String p,Map<String,dynamic>q)=>_request('GET',_uri(p,q));Future<Map<String,dynamic>>post(String p,Map<String,dynamic>b)=>_request('POST',_uri(p),b);Future<Map<String,dynamic>>patch(String p,Map<String,dynamic>b)=>_request('PATCH',_uri(p),b);Future<Map<String,dynamic>>delete(String p,Map<String,dynamic>b)=>_request('DELETE',_uri(p),b);Future<Map<String,dynamic>>_request(String m,Uri u,[Map<String,dynamic>?b])async{final c=HttpClient();try{final r=await c.openUrl(m,u);r.headers.contentType=ContentType.json;if(b!=null)r.write(jsonEncode(b));final s=await r.close(),txt=await utf8.decoder.bind(s).join(),d=txt.isEmpty?<String,dynamic>{}:Map<String,dynamic>.from(jsonDecode(txt));if(s.statusCode<200||s.statusCode>=300)throw Exception(d['message']??'API hatası (${s.statusCode})');return d;}finally{c.close(force:true);}}}
